<?php

use App\Models\Category;
use App\Models\Product;

test('admin can list categories', function () {
    Category::factory()->create(['name' => 'Electronics']);

    assertAdminIndexRenders('admin.categories.index', 'Admin/Categories/Index', 'categories', 1);
});

test('admin categories index paginates results instead of loading them all at once', function () {
    assertIndexPaginates('admin.categories.index', 'categories', fn () => Category::factory()->count(20)->create());
});

test('admin can filter categories by parent_id', function () {
    $parent = Category::factory()->create();
    $otherParent = Category::factory()->create();
    Category::factory()->create(['parent_id' => $parent->id]);
    Category::factory()->create(['parent_id' => $otherParent->id]);

    assertAdminIndexFiltersBy('admin.categories.index', 'categories', ['parent_id' => $parent->id], 'parent_id', $parent->id);
});

test('admin can filter categories by search', function () {
    Category::factory()->create(['name' => 'Electronics']);
    Category::factory()->create(['name' => 'Furniture']);

    assertAdminIndexFiltersBy('admin.categories.index', 'categories', ['search' => 'Electro'], 'name', 'Electronics');
});

test('non-admin cannot list categories', function () {
    assertNonAdminCannotView('admin.categories.index');
});

test('admin can render the create category page', function () {
    $category = Category::factory()->create();

    assertAdminCanRenderCreatePage('admin.categories.create', 'Admin/Categories/Create', 'categories', $category);
});

test('admin can render the edit category page', function () {
    $category = Category::factory()->create();

    assertAdminCanRenderEditPage('admin.categories.edit', 'Admin/Categories/Edit', 'category', $category);
});

test('non-admin cannot view the category create or edit pages', function () {
    assertNonAdminCannotViewCreateOrEditPages('categories', Category::factory()->create());
});

test('admin can create a category', function () {
    $admin = actingAsAdmin();
    $parent = Category::factory()->create();

    $response = $this->actingAs($admin)->post(route('admin.categories.store'), [
        'parent_id' => $parent->id,
        'name' => 'New Category',
        'slug' => 'new-category',
    ]);

    $response->assertRedirect(route('admin.categories.index'));
    $this->assertDatabaseHas('categories', ['slug' => 'new-category', 'parent_id' => $parent->id]);
});

test('admin can change a categorys parent on update', function () {
    $originalParent = Category::factory()->create();
    $newParent = Category::factory()->create();
    $category = Category::factory()->create(['parent_id' => $originalParent->id]);

    assertAdminCanUpdateForeignKeyOnResource('categories', 'categories', 'parent_id', $category, $newParent);
});

test('admin can clear a categorys parent on update', function () {
    $parent = Category::factory()->create();
    $category = Category::factory()->create(['parent_id' => $parent->id]);

    assertAdminCanUpdateForeignKeyOnResource('categories', 'categories', 'parent_id', $category, null);
});

test('category slugs are auto-generated and deduplicated', function () {
    $admin = actingAsAdmin();

    assertSlugIsAutoGeneratedAndDeduplicated(
        Category::class,
        fn (array $attributes) => $this->actingAs($admin)->post(route('admin.categories.store'), $attributes),
        fn ($category, array $attributes) => $this->actingAs($admin)->patch(route('admin.categories.update', $category), $attributes),
    );
});

test('admin can update a category', function () {
    $admin = actingAsAdmin();
    $category = Category::factory()->create(['name' => 'Old Name']);

    $response = $this->actingAs($admin)->patch(route('admin.categories.update', $category), [
        'name' => 'New Name',
    ]);

    $response->assertRedirect(route('admin.categories.index'));
    $this->assertDatabaseHas('categories', ['id' => $category->id, 'name' => 'New Name']);
});

test('admin can delete an empty category', function () {
    assertAdminCanDeleteResource('categories', Category::factory()->create());
});

test('admin cannot delete a category that still has products', function () {
    $category = Category::factory()->create();
    Product::factory()->create(['category_id' => $category->id]);

    assertAdminCannotDeleteResourceInUse('categories', $category, 'category');
});

test('admin cannot delete a category that still has child categories', function () {
    $parent = Category::factory()->create();
    Category::factory()->create(['parent_id' => $parent->id]);

    assertAdminCannotDeleteResourceInUse('categories', $parent, 'category');
});

test('non-admin cannot create update or delete categories', function () {
    assertNonAdminCannotMutate('categories', Category::factory()->create());
});
