<?php

use App\Models\Category;
use App\Models\OrderItem;
use App\Models\Product;

test('admin can list products including inactive and out-of-stock ones', function () {
    Product::factory()->create(['name' => 'Active Widget', 'is_active' => true]);
    Product::factory()->create(['name' => 'Inactive Widget', 'is_active' => false]);

    assertAdminIndexRenders('admin.products.index', 'Admin/Products/Index', 'products', 2);
});

test('admin products index paginates results instead of loading them all at once', function () {
    assertIndexPaginates('admin.products.index', 'products', fn () => Product::factory()->count(20)->create());
});

test('non-admin cannot list products', function () {
    assertNonAdminCannotView('admin.products.index');
});

test('admin can filter products by stock_status', function () {
    Product::factory()->create(['name' => 'Low Stock Item', 'stock' => 3]);
    Product::factory()->create(['name' => 'Out Of Stock Item', 'stock' => 0]);
    Product::factory()->create(['name' => 'Plenty In Stock', 'stock' => 50]);

    assertAdminIndexFiltersBy('admin.products.index', 'products', ['stock_status' => 'low'], 'name', 'Low Stock Item');
    assertAdminIndexFiltersBy('admin.products.index', 'products', ['stock_status' => 'out'], 'name', 'Out Of Stock Item');
});

test('admin can filter products by search', function () {
    Product::factory()->create(['name' => 'Wireless Keyboard']);
    Product::factory()->create(['name' => 'Desk Lamp']);

    assertAdminIndexFiltersBy('admin.products.index', 'products', ['search' => 'Keyboard'], 'name', 'Wireless Keyboard');
});

test('admin can filter products by category_id', function () {
    $category = Category::factory()->create();
    $otherCategory = Category::factory()->create();
    Product::factory()->create(['category_id' => $category->id]);
    Product::factory()->create(['category_id' => $otherCategory->id]);

    assertAdminIndexFiltersBy('admin.products.index', 'products', ['category_id' => $category->id], 'category_id', $category->id);
});

test('admin can render the create product page', function () {
    $category = Category::factory()->create();

    assertAdminCanRenderCreatePage('admin.products.create', 'Admin/Products/Create', 'categories', $category);
});

test('admin can render the edit product page', function () {
    $product = Product::factory()->create();

    assertAdminCanRenderEditPage('admin.products.edit', 'Admin/Products/Edit', 'product', $product);
});

test('non-admin cannot view the product create or edit pages', function () {
    assertNonAdminCannotViewCreateOrEditPages('products', Product::factory()->create());
});

test('admin can create a product', function () {
    $admin = actingAsAdmin();
    $category = Category::factory()->create();

    $response = $this->actingAs($admin)->post(route('admin.products.store'), [
        'category_id' => $category->id,
        'name' => 'New Gadget',
        'slug' => 'new-gadget',
        'price' => 49.99,
        'stock' => 10,
        'is_active' => true,
    ]);

    $product = Product::where('slug', 'new-gadget')->firstOrFail();
    $response->assertRedirect(route('admin.products.edit', $product));
    $this->assertDatabaseHas('products', [
        'slug' => 'new-gadget',
        'name' => 'New Gadget',
        'category_id' => $category->id,
    ]);
});

test('admin can change a products category on update', function () {
    $originalCategory = Category::factory()->create();
    $newCategory = Category::factory()->create();
    $product = Product::factory()->create(['category_id' => $originalCategory->id]);

    assertAdminCanUpdateForeignKeyOnResource('products', 'products', 'category_id', $product, $newCategory);
});

test('admin can clear a products category on update', function () {
    $category = Category::factory()->create();
    $product = Product::factory()->create(['category_id' => $category->id]);

    assertAdminCanUpdateForeignKeyOnResource('products', 'products', 'category_id', $product, null);
});

test('product slugs are auto-generated and deduplicated', function () {
    $admin = actingAsAdmin();

    assertSlugIsAutoGeneratedAndDeduplicated(
        Product::class,
        fn (array $attributes) => $this->actingAs($admin)->post(route('admin.products.store'), array_merge(['price' => 9.99], $attributes)),
        fn ($product, array $attributes) => $this->actingAs($admin)->patch(route('admin.products.update', $product), $attributes),
    );
});

test('admin can create a product with a blank stock field and it defaults to zero', function () {
    $admin = actingAsAdmin();

    // The admin form always submits `stock` (as an empty string when left
    // blank), which Laravel's ConvertEmptyStringsToNull middleware turns into
    // null before validation - this reproduces that exact payload shape,
    // rather than omitting the key entirely as a raw API test might.
    $response = $this->actingAs($admin)->post(route('admin.products.store'), [
        'name' => 'No Stock Yet',
        'price' => 9.99,
        'stock' => '',
    ]);

    $product = Product::where('name', 'No Stock Yet')->firstOrFail();
    $response->assertRedirect(route('admin.products.edit', $product));
    $this->assertDatabaseHas('products', ['name' => 'No Stock Yet', 'stock' => 0]);
});

test('admin clearing stock on update defaults it back to zero', function () {
    $admin = actingAsAdmin();
    $product = Product::factory()->create(['stock' => 25]);

    $response = $this->actingAs($admin)->patch(route('admin.products.update', $product), [
        'stock' => '',
    ]);

    $response->assertRedirect(route('admin.products.index'));
    $this->assertDatabaseHas('products', ['id' => $product->id, 'stock' => 0]);
});

test('admin can update a product', function () {
    $admin = actingAsAdmin();
    $product = Product::factory()->create(['name' => 'Old Name']);

    $response = $this->actingAs($admin)->patch(route('admin.products.update', $product), [
        'name' => 'New Name',
    ]);

    $response->assertRedirect(route('admin.products.index'));
    $this->assertDatabaseHas('products', ['id' => $product->id, 'name' => 'New Name']);
});

test('admin can delete a product', function () {
    assertAdminCanDeleteResource('products', Product::factory()->create());
});

test('admin cannot delete a product that has existing orders', function () {
    $product = Product::factory()->create();
    OrderItem::factory()->create(['product_id' => $product->id]);

    assertAdminCannotDeleteResourceInUse('products', $product, 'product');
});

test('non-admin cannot create update or delete products', function () {
    assertNonAdminCannotMutate('products', Product::factory()->create());
});
