-- =====================================================================
-- Grocery catalog seed data - Arabic content (plain MySQL, no Laravel/artisan involved)
-- بيانات تعبئة كتالوج منتجات البقالة باللغة العربية
-- =====================================================================
-- Target schema: categories, products, product_images, product_variants
-- (see database/migrations/2026_07_19_*.php for column definitions)
--
-- Usage:
--   mysql -u root -p laravel_estore < database/sql/grocery_products_seed.sql
--
-- Slugs are kept in Latin/ASCII form (fresh-bananas, cheese, ...) for
-- URL-friendliness; all human-readable text (names, descriptions,
-- brand/unit metadata) is in Arabic. Requires a utf8mb4 connection
-- (the project's default DB_CHARSET), hence the SET NAMES below.
--
-- WARNING: the TRUNCATE block below wipes any existing rows in these
-- four tables before reseeding, so the explicit IDs used further down
-- stay predictable. Comment it out if you want to keep existing data
-- (in that case, drop the explicit `id` values and adapt the product_id
-- references accordingly).
-- =====================================================================

SET NAMES utf8mb4;

START TRANSACTION;

-- Plain DELETE (not TRUNCATE) in child-to-parent order, so this works
-- even if your SQL client runs each statement in its own connection
-- (which would otherwise drop a session-level FOREIGN_KEY_CHECKS=0).
DELETE FROM product_variants;
DELETE FROM product_images;
DELETE FROM products;
DELETE FROM categories;

-- ---------------------------------------------------------------------
-- Categories: 8 top-level departments + 22 sub-categories
-- التصنيفات: 8 أقسام رئيسية + 22 تصنيفاً فرعياً
-- ---------------------------------------------------------------------

INSERT INTO categories (id, parent_id, name, slug, description, created_at, updated_at) VALUES
(1, NULL, 'الفواكه والخضروات', 'fruits-vegetables', 'منتجات طازجة وموسمية يتم توريدها يومياً.', NOW(), NOW()),
(2, NULL, 'منتجات الألبان والبيض', 'dairy-eggs', 'الحليب والجبن والقشدة والبيض الطازج.', NOW(), NOW()),
(3, NULL, 'المخبوزات', 'bakery', 'خبز ومعجنات طازجة يومياً.', NOW(), NOW()),
(4, NULL, 'اللحوم والمأكولات البحرية', 'meat-seafood', 'الدواجن واللحوم الحمراء والمأكولات البحرية الطازجة.', NOW(), NOW()),
(5, NULL, 'المواد الغذائية الأساسية', 'pantry-staples', 'الأرز والمعكرونة والمعلبات ومستلزمات الطبخ الأساسية.', NOW(), NOW()),
(6, NULL, 'المشروبات', 'beverages', 'العصائر والمشروبات الغازية والمياه والقهوة والشاي.', NOW(), NOW()),
(7, NULL, 'الوجبات الخفيفة', 'snacks', 'رقائق البطاطس والشوكولاتة والحلويات.', NOW(), NOW()),
(8, NULL, 'الأطعمة المجمدة', 'frozen-foods', 'خضروات وحلويات مجمدة.', NOW(), NOW());

INSERT INTO categories (id, parent_id, name, slug, description, created_at, updated_at) VALUES
(9,  1, 'فواكه طازجة',            'fresh-fruits',              'فواكه موسمية مقطوفة بعناية.', NOW(), NOW()),
(10, 1, 'خضروات طازجة',           'fresh-vegetables',          'خضروات محلية المصدر.', NOW(), NOW()),
(11, 2, 'الحليب والقشدة',          'milk-cream',                'حليب وقشدة طازجة وطويلة الصلاحية.', NOW(), NOW()),
(12, 2, 'الجبن',                  'cheese',                    'جبن كتلة وشرائح ومبشور.', NOW(), NOW()),
(13, 2, 'البيض',                  'eggs',                      'بيض حر المراعي وعضوي.', NOW(), NOW()),
(14, 3, 'الخبز',                  'bread',                     'أرغفة مقطعة وخبز صغير.', NOW(), NOW()),
(15, 3, 'المعجنات والكعك',         'pastries-cakes',            'حلويات مخبوزة شهية.', NOW(), NOW()),
(16, 4, 'الدواجن',                'poultry',                   'الدجاج والديك الرومي.', NOW(), NOW()),
(17, 4, 'لحم البقر والضأن',        'beef-lamb',                 'قطع لحم أحمر طازجة.', NOW(), NOW()),
(18, 4, 'المأكولات البحرية',       'seafood',                   'أسماك طازجة ومحار.', NOW(), NOW()),
(19, 5, 'الأرز والحبوب',           'rice-grains',               'الأرز والكينوا وحبوب أخرى.', NOW(), NOW()),
(20, 5, 'المعكرونة والنودلز',      'pasta-noodles',             'معكرونة ونودلز جافة.', NOW(), NOW()),
(21, 5, 'المعلبات',                'canned-jarred-goods',       'أطعمة معلبة طويلة الصلاحية.', NOW(), NOW()),
(22, 5, 'زيوت الطبخ والخل',        'cooking-oils-vinegars',     'زيوت وخل وصلصات تتبيل.', NOW(), NOW()),
(23, 6, 'العصائر',                 'juices',                    'عصائر فواكه طازجة وطويلة الصلاحية.', NOW(), NOW()),
(24, 6, 'المشروبات الغازية',       'soft-drinks',               'مشروبات غازية منعشة.', NOW(), NOW()),
(25, 6, 'المياه',                  'water',                     'مياه عادية وغازية.', NOW(), NOW()),
(26, 6, 'القهوة والشاي',           'coffee-tea',                'قهوة مطحونة وأكياس شاي.', NOW(), NOW()),
(27, 7, 'رقائق البطاطس',           'chips-crisps',              'وجبات خفيفة مالحة من البطاطس والذرة.', NOW(), NOW()),
(28, 7, 'الشوكولاتة والحلويات',    'chocolate-candy',           'ألواح شوكولاتة وحلويات متنوعة.', NOW(), NOW()),
(29, 8, 'خضروات مجمدة',            'frozen-vegetables',         'خضروات مجمدة سريعاً للحفاظ على نضارتها.', NOW(), NOW()),
(30, 8, 'الآيس كريم',              'ice-cream',                 'حلويات مجمدة.', NOW(), NOW());

-- ---------------------------------------------------------------------
-- Products: 46 grocery products across the sub-categories above
-- المنتجات: 46 منتجاً موزعة على التصنيفات الفرعية أعلاه
-- ---------------------------------------------------------------------

INSERT INTO products
    (id, category_id, name, slug, price, short_description, description, is_active, stock, metadata, created_at, updated_at)
VALUES
(1,  9, 'موز طازج', 'fresh-bananas', 1.99,
    'موز حلو ناضج يُباع بالكيلوغرام.',
    'موز ناضج طبيعياً، مصدر ممتاز للبوتاسيوم والألياف. مثالي للوجبات الخفيفة والعصائر والخَبز.',
    1, 240, JSON_OBJECT('brand', 'مزرعة طازجة', 'unit', '1 كجم'), NOW(), NOW()),
(2,  9, 'تفاح غالا', 'gala-apples', 2.49,
    'تفاح غالا مقرمش وعصيري.',
    'تفاح غالا حلو ومقرمش يُقطف في ذروة نضجه. مثالي لصناديق الغداء أو خَبز الفطائر.',
    1, 180, JSON_OBJECT('brand', 'المروج الخضراء', 'unit', '1 كجم'), NOW(), NOW()),
(3,  9, 'برتقال أبو سرة', 'navel-oranges', 2.99,
    'برتقال أبو سرة عصيري بدون بذور.',
    'برتقال أبو سرة بدون بذور وغني بفيتامين سي. سهل التقشير ومثالي لعصير طازج.',
    1, 150, JSON_OBJECT('brand', 'المروج الخضراء', 'unit', '1 كجم'), NOW(), NOW()),
(4,  10, 'طماطم روما', 'roma-tomatoes', 1.79,
    'طماطم روما متماسكة وغنية بالنكهة.',
    'طماطم روما بنكهة غنية، مثالية للصلصات والسلطات والتحميص.',
    1, 200, JSON_OBJECT('brand', 'مزرعة طازجة', 'unit', '1 كجم'), NOW(), NOW()),
(5,  10, 'سبانخ صغيرة', 'baby-spinach', 2.29,
    'أوراق سبانخ صغيرة طرية ومغسولة.',
    'أوراق سبانخ صغيرة مغسولة مسبقاً وجاهزة للأكل. رائعة في السلطات والعصائر أو مقلية كطبق جانبي.',
    1, 120, JSON_OBJECT('brand', 'المروج الخضراء', 'unit', '200 جم'), NOW(), NOW()),
(6,  10, 'جزر', 'carrots', 1.49,
    'جزر طازج حلو ومقرمش.',
    'جزر طازج كامل، مثالي للوجبات الخفيفة أو التحميص أو إضافته لليخنات والشوربات.',
    1, 220, JSON_OBJECT('brand', 'مزرعة طازجة', 'unit', '1 كجم'), NOW(), NOW()),
(7,  11, 'حليب كامل الدسم 1 لتر', 'whole-milk-1l', 1.89,
    'حليب كامل الدسم طازج ومبستر.',
    'حليب كامل الدسم كريمي ومبستر من أبقار تتغذى على العشب. أساسي يومي للمطبخ.',
    1, 300, JSON_OBJECT('brand', 'دايري بيور', 'unit', '1 لتر'), NOW(), NOW()),
(8,  11, 'قشدة كثيفة 500 مل', 'heavy-cream-500ml', 3.49,
    'قشدة كثيفة وغنية للطبخ والخَبز.',
    'قشدة كثيفة وغنية تُخفق جيداً وتضيف قواماً غنياً للصلصات والشوربات والحلويات.',
    1, 90, JSON_OBJECT('brand', 'دايري بيور', 'unit', '500 مل'), NOW(), NOW()),
(9,  12, 'جبنة تشيدر كتلة 200 جم', 'cheddar-cheese-block-200g', 4.99,
    'كتلة جبنة تشيدر ناضجة.',
    'جبنة تشيدر معتقة بنكهة حادة وغنية. رائعة للسندويشات والطبخ.',
    1, 140, JSON_OBJECT('brand', 'دايري بيور', 'unit', '200 جم'), NOW(), NOW()),
(10, 12, 'جبنة موزاريلا 250 جم', 'mozzarella-cheese-250g', 4.49,
    'جبنة موزاريلا طرية ومبشورة.',
    'جبنة موزاريلا مبشورة تذوب بشكل رائع، مثالية للبيتزا وأطباق المعكرونة المخبوزة.',
    1, 130, JSON_OBJECT('brand', 'دايري بيور', 'unit', '250 جم'), NOW(), NOW()),
(11, 13, 'بيض حر المراعي (عبوة 12)', 'free-range-eggs-12-pack', 3.99,
    'دزينة من بيض حر المراعي.',
    'بيض من دجاج حر يتربى في مراعٍ مفتوحة. صفار غني، مثالي لأي وصفة.',
    1, 160, JSON_OBJECT('brand', 'الحصاد الذهبي', 'unit', 'عبوة 12'), NOW(), NOW()),
(12, 13, 'بيض عضوي (عبوة 6)', 'organic-eggs-6-pack', 3.49,
    'بيض عضوي معتمد، عبوة من 6.',
    'بيض عضوي معتمد من دجاج يتغذى على نظام عضوي كامل بدون مضادات حيوية.',
    1, 110, JSON_OBJECT('brand', 'الحصاد الذهبي', 'unit', 'عبوة 6'), NOW(), NOW()),
(13, 14, 'رغيف خبز القمح الكامل', 'whole-wheat-bread-loaf', 2.49,
    'خبز قمح كامل طري ومُشبع.',
    'رغيف خبز قمح كامل طازج، غني بالألياف ومثالي للسندويشات اليومية.',
    1, 100, JSON_OBJECT('brand', 'باكرز رو', 'unit', '750 جم'), NOW(), NOW()),
(14, 14, 'خبز التوست الأبيض', 'white-sandwich-bread', 1.99,
    'خبز توست أبيض طري.',
    'خبز أبيض طري كلاسيكي، مقطع وجاهز للسندويشات أو التحميص.',
    1, 130, JSON_OBJECT('brand', 'باكرز رو', 'unit', '700 جم'), NOW(), NOW()),
(15, 15, 'كرواسون بالشوكولاتة', 'chocolate-croissant', 2.29,
    'كرواسون بالزبدة محشو بالشوكولاتة.',
    'كرواسون مقرمش بالزبدة محشو بشوكولاتة غنية. يُخبز طازجاً يومياً.',
    1, 80, JSON_OBJECT('brand', 'باكرز رو', 'unit', 'قطعة'), NOW(), NOW()),
(16, 15, 'مافن التوت الأزرق', 'blueberry-muffin', 1.99,
    'مافن رطب مليء بالتوت الأزرق.',
    'مافن طري ورطب محمّل بالتوت الأزرق العصيري. مثالي للفطور أو وجبة خفيفة.',
    1, 90, JSON_OBJECT('brand', 'باكرز رو', 'unit', 'قطعة'), NOW(), NOW()),
(17, 16, 'صدور دجاج 1 كجم', 'chicken-breast-1kg', 6.99,
    'صدور دجاج بدون جلد وعظم.',
    'شرائح صدور دجاج طازجة بدون جلد وعظم. بروتين قليل الدهون ومتعدد الاستخدامات.',
    1, 100, JSON_OBJECT('brand', 'مزرعة الدواجن', 'unit', '1 كجم'), NOW(), NOW()),
(18, 16, 'دجاجة كاملة 1.5 كجم', 'whole-chicken-1-5kg', 8.49,
    'دجاجة كاملة طازجة وجاهزة للشوي.',
    'دجاجة كاملة طازجة، مثالية للشوي أو التحضير على الفحم أو تحضير المرق.',
    1, 70, JSON_OBJECT('brand', 'مزرعة الدواجن', 'unit', '1.5 كجم'), NOW(), NOW()),
(19, 17, 'لحم بقري مفروم 500 جم', 'ground-beef-500g', 5.99,
    'لحم بقري مفروم طازج قليل الدهن.',
    'لحم بقري مفروم طازج بنسبة دهن متوازنة، رائع للبرغر وكرات اللحم والصلصات.',
    1, 90, JSON_OBJECT('brand', 'برايم كتس', 'unit', '500 جم'), NOW(), NOW()),
(20, 17, 'قطع ضأن 500 جم', 'lamb-chops-500g', 9.99,
    'قطع ضأن طرية من الخاصرة.',
    'قطع ضأن طرية من الخاصرة، منظفة جيداً وجاهزة للشوي أو المقلاة.',
    1, 60, JSON_OBJECT('brand', 'برايم كتس', 'unit', '500 جم'), NOW(), NOW()),
(21, 18, 'شرائح سلمون طازج 300 جم', 'fresh-salmon-fillet-300g', 7.99,
    'شريحة سلمون طازجة بالجلد.',
    'شريحة سلمون طازجة بالجلد وغنية بأوميغا 3. رائعة للشوي أو الخَبز في الفرن.',
    1, 70, JSON_OBJECT('brand', 'صيد المحيط', 'unit', '300 جم'), NOW(), NOW()),
(22, 18, 'جمبري 500 جم', 'shrimp-500g', 8.99,
    'جمبري مقشر ومنظف.',
    'جمبري مقشر ومنظف، سريع التحضير ومثالي للقلي السريع أو المعكرونة.',
    1, 65, JSON_OBJECT('brand', 'صيد المحيط', 'unit', '500 جم'), NOW(), NOW()),
(23, 19, 'أرز بسمتي 5 كجم', 'basmati-rice-5kg', 12.99,
    'أرز بسمتي طويل الحبة وعطري.',
    'أرز بسمتي فاخر طويل الحبة برائحة عطرية، مثالي للوجبات اليومية.',
    1, 150, JSON_OBJECT('brand', 'بانتري كو', 'unit', '5 كجم'), NOW(), NOW()),
(24, 19, 'كينوا 500 جم', 'quinoa-500g', 5.49,
    'كينوا بيضاء غنية بالبروتين.',
    'كينوا بيضاء مغذية، بروتين نباتي كامل رائع للسلطات والأطباق الصحية.',
    1, 100, JSON_OBJECT('brand', 'بانتري كو', 'unit', '500 جم'), NOW(), NOW()),
(25, 20, 'سباغيتي 500 جم', 'spaghetti-500g', 1.79,
    'سباغيتي كلاسيكية من قمح الدوروم.',
    'سباغيتي إيطالية كلاسيكية مصنوعة من سميد قمح الدوروم. تُطهى بقوام مثالي متماسك.',
    1, 200, JSON_OBJECT('brand', 'بانتري كو', 'unit', '500 جم'), NOW(), NOW()),
(26, 20, 'معكرونة بيني 500 جم', 'penne-pasta-500g', 1.79,
    'معكرونة بيني مضلعة.',
    'معكرونة بيني مضلعة تحتفظ بالصلصة بشكل رائع، مثالية للأطباق المخبوزة والعشاء السريع.',
    1, 190, JSON_OBJECT('brand', 'بانتري كو', 'unit', '500 جم'), NOW(), NOW()),
(27, 21, 'حمص معلب 400 جم', 'canned-chickpeas-400g', 0.99,
    'حمص جاهز للأكل معلب في الماء.',
    'حمص مطبوخ ومعلب في الماء، جاهز للسلطات أو الحمص أو الأطباق الحارة.',
    1, 220, JSON_OBJECT('brand', 'بانتري كو', 'unit', '400 جم'), NOW(), NOW()),
(28, 21, 'طماطم مقطعة معلبة 400 جم', 'diced-tomatoes-can-400g', 0.89,
    'طماطم مقطعة معلبة في عصيرها.',
    'طماطم ناضجة مقطعة ومعلبة في عصيرها الطبيعي، أساسية للصلصات واليخنات.',
    1, 230, JSON_OBJECT('brand', 'بانتري كو', 'unit', '400 جم'), NOW(), NOW()),
(29, 22, 'زيت زيتون بكر ممتاز 1 لتر', 'extra-virgin-olive-oil-1l', 8.99,
    'زيت زيتون بكر ممتاز معصور على البارد.',
    'زيت زيتون بكر ممتاز معصور على البارد بنكهة فاكهية ناعمة. رائع للطبخ والصلصات.',
    1, 110, JSON_OBJECT('brand', 'أوليفيرا', 'unit', '1 لتر'), NOW(), NOW()),
(30, 22, 'زيت دوار الشمس 1 لتر', 'sunflower-oil-1l', 3.49,
    'زيت دوار الشمس خفيف ومحايد الطعم.',
    'زيت دوار الشمس خفيف ومحايد مناسب للقلي والطبخ اليومي.',
    1, 140, JSON_OBJECT('brand', 'بانتري كو', 'unit', '1 لتر'), NOW(), NOW()),
(31, 23, 'عصير برتقال 1 لتر', 'orange-juice-1l', 2.99,
    'عصير برتقال طازج معصور.',
    'عصير برتقال غير مركّز، معصور طازجاً وغني بفيتامين سي.',
    1, 130, JSON_OBJECT('brand', 'سني غروف', 'unit', '1 لتر'), NOW(), NOW()),
(32, 23, 'عصير تفاح 1 لتر', 'apple-juice-1l', 2.79,
    'عصير تفاح صافٍ وحلو.',
    'عصير تفاح صافٍ معصور من تفاح مقرمش، بدون سكر مضاف.',
    1, 120, JSON_OBJECT('brand', 'سني غروف', 'unit', '1 لتر'), NOW(), NOW()),
(33, 24, 'كولا 1.5 لتر', 'cola-1-5l', 1.49,
    'مشروب كولا غازي كلاسيكي.',
    'مشروب كولا كلاسيكي، يُفضل تقديمه بارداً.',
    1, 180, JSON_OBJECT('brand', 'فيز كو', 'unit', '1.5 لتر'), NOW(), NOW()),
(34, 24, 'صودا الليمون 1.5 لتر', 'lemon-soda-1-5l', 1.49,
    'صودا بنكهة الليمون منعشة.',
    'مشروب غازي منعش بنكهة الليمون والليم.',
    1, 170, JSON_OBJECT('brand', 'فيز كو', 'unit', '1.5 لتر'), NOW(), NOW()),
(35, 25, 'مياه غازية 1 لتر', 'sparkling-water-1l', 0.99,
    'مياه غازية طبيعياً.',
    'مياه معدنية غازية طبيعياً بفقاعات ناعمة وبدون نكهة.',
    1, 200, JSON_OBJECT('brand', 'ألباين سبرينغ', 'unit', '1 لتر'), NOW(), NOW()),
(36, 25, 'مياه شرب طبيعية 6×500 مل', 'natural-spring-water-6x500ml', 2.49,
    'مياه شرب طبيعية عادية، عبوة متعددة.',
    'مياه شرب طبيعية عادية معبأة من المصدر، تُباع في عبوة من 6 قوارير × 500 مل.',
    1, 160, JSON_OBJECT('brand', 'ألباين سبرينغ', 'unit', '6 × 500 مل'), NOW(), NOW()),
(37, 26, 'قهوة مطحونة 250 جم', 'ground-coffee-250g', 5.99,
    'قهوة مطحونة متوسطة التحميص.',
    'قهوة متوسطة التحميص ومطحونة طازجة بنكهة ناعمة ومتوازنة.',
    1, 100, JSON_OBJECT('brand', 'برو هاوس', 'unit', '250 جم'), NOW(), NOW()),
(38, 26, 'أكياس شاي أخضر (عبوة 20)', 'green-tea-bags-20-pack', 3.49,
    'أكياس شاي أخضر خفيفة ومنعشة.',
    'أكياس شاي أخضر خفيفة ومنعشة وغنية بمضادات الأكسدة. عبوة من 20 كيساً.',
    1, 140, JSON_OBJECT('brand', 'برو هاوس', 'unit', 'عبوة 20'), NOW(), NOW()),
(39, 27, 'رقائق بطاطس كلاسيكية 150 جم', 'classic-potato-chips-150g', 1.99,
    'رقائق بطاطس مقرمشة ومملحة.',
    'رقائق بطاطس رفيعة ومقرمشة ومملحة قليلاً بالنكهة الكلاسيكية.',
    1, 200, JSON_OBJECT('brand', 'سناك تايم', 'unit', '150 جم'), NOW(), NOW()),
(40, 27, 'رقائق تورتيلا 200 جم', 'tortilla-chips-200g', 2.29,
    'رقائق تورتيلا ذرة مقرمشة.',
    'رقائق تورتيلا ذرة مقرمشة، مثالية مع الصلصة أو الغواكامولي أو بمفردها.',
    1, 180, JSON_OBJECT('brand', 'سناك تايم', 'unit', '200 جم'), NOW(), NOW()),
(41, 28, 'لوح شوكولاتة بالحليب 100 جم', 'milk-chocolate-bar-100g', 1.49,
    'شوكولاتة بالحليب ناعمة وكريمية.',
    'لوح شوكولاتة بالحليب ناعم وكريمي مصنوع من زبدة الكاكاو الحقيقية.',
    1, 220, JSON_OBJECT('brand', 'كاكاو بليس', 'unit', '100 جم'), NOW(), NOW()),
(42, 28, 'حلوى جيلي متنوعة 250 جم', 'assorted-gummy-candy-250g', 2.49,
    'حلوى جيلي بنكهات الفواكه.',
    'تشكيلة ملونة من حلوى الجيلي بنكهات الفواكه المتنوعة.',
    1, 150, JSON_OBJECT('brand', 'كاكاو بليس', 'unit', '250 جم'), NOW(), NOW()),
(43, 29, 'خضروات مشكلة مجمدة 1 كجم', 'frozen-mixed-vegetables-1kg', 2.99,
    'خليط من الخضروات المجمدة سريعاً.',
    'خليط عملي من الجزر والبازلاء والذرة والفاصولياء الخضراء، مجمد سريعاً للحفاظ على القيمة الغذائية.',
    1, 130, JSON_OBJECT('brand', 'تشيل هارفست', 'unit', '1 كجم'), NOW(), NOW()),
(44, 29, 'بازلاء مجمدة 500 جم', 'frozen-peas-500g', 1.99,
    'بازلاء حلوة مجمدة سريعاً.',
    'بازلاء حديقة حلوة، مجمدة سريعاً بعد القطف مباشرة للحفاظ على نضارتها.',
    1, 160, JSON_OBJECT('brand', 'تشيل هارفست', 'unit', '500 جم'), NOW(), NOW()),
(45, 30, 'آيس كريم فانيليا 1 لتر', 'vanilla-ice-cream-1l', 4.49,
    'آيس كريم فانيليا كلاسيكي وكريمي.',
    'آيس كريم فانيليا غني وكريمي مصنوع من الفانيليا الحقيقية.',
    1, 90, JSON_OBJECT('brand', 'تشيل بايت', 'unit', '1 لتر'), NOW(), NOW()),
(46, 30, 'آيس كريم شوكولاتة 1 لتر', 'chocolate-ice-cream-1l', 4.49,
    'آيس كريم شوكولاتة غني.',
    'آيس كريم شوكولاتة فاخر مصنوع من الكاكاو الحقيقي بطعم غني وناعم.',
    1, 90, JSON_OBJECT('brand', 'تشيل بايت', 'unit', '1 لتر'), NOW(), NOW());

-- ---------------------------------------------------------------------
-- Product images: 2 per product (1 primary + 1 secondary)
-- Real food photos via LoremFlickr, matched by an English keyword tag
-- per product and pinned with `lock` so the same photo keeps showing
-- on every reload (LoremFlickr returns a random match otherwise).
-- NOTE: these are hotlinked third-party stock photos for seeding/demo
-- purposes only - for production, download and host the images
-- yourself instead of relying on an external service long-term.
-- صور المنتجات: صورتان حقيقيتان لكل منتج، مصدرها LoremFlickr حسب كلمة
-- مفتاحية إنجليزية تعبّر عن المنتج
-- ---------------------------------------------------------------------

INSERT INTO product_images (product_id, url, alt_text, sort_order, is_primary, created_at, updated_at) VALUES
(1,  'https://loremflickr.com/800/800/banana?lock=1',            'موز طازج', 0, 1, NOW(), NOW()),
(1,  'https://loremflickr.com/800/800/banana?lock=101',          'موز طازج - صورة إضافية', 1, 0, NOW(), NOW()),
(2,  'https://loremflickr.com/800/800/apple?lock=2',             'تفاح غالا', 0, 1, NOW(), NOW()),
(2,  'https://loremflickr.com/800/800/apple?lock=102',           'تفاح غالا - صورة إضافية', 1, 0, NOW(), NOW()),
(3,  'https://loremflickr.com/800/800/orange,fruit?lock=3',      'برتقال أبو سرة', 0, 1, NOW(), NOW()),
(3,  'https://loremflickr.com/800/800/orange,fruit?lock=103',    'برتقال أبو سرة - صورة إضافية', 1, 0, NOW(), NOW()),
(4,  'https://loremflickr.com/800/800/tomato?lock=4',            'طماطم روما', 0, 1, NOW(), NOW()),
(4,  'https://loremflickr.com/800/800/tomato?lock=104',          'طماطم روما - صورة إضافية', 1, 0, NOW(), NOW()),
(5,  'https://loremflickr.com/800/800/spinach?lock=5',           'سبانخ صغيرة', 0, 1, NOW(), NOW()),
(5,  'https://loremflickr.com/800/800/spinach?lock=105',         'سبانخ صغيرة - صورة إضافية', 1, 0, NOW(), NOW()),
(6,  'https://loremflickr.com/800/800/carrot?lock=6',            'جزر', 0, 1, NOW(), NOW()),
(6,  'https://loremflickr.com/800/800/carrot?lock=106',          'جزر - صورة إضافية', 1, 0, NOW(), NOW()),
(7,  'https://loremflickr.com/800/800/milk?lock=7',              'حليب كامل الدسم 1 لتر', 0, 1, NOW(), NOW()),
(7,  'https://loremflickr.com/800/800/milk?lock=107',            'حليب كامل الدسم 1 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(8,  'https://loremflickr.com/800/800/cream,dairy?lock=8',       'قشدة كثيفة 500 مل', 0, 1, NOW(), NOW()),
(8,  'https://loremflickr.com/800/800/cream,dairy?lock=108',     'قشدة كثيفة 500 مل - صورة إضافية', 1, 0, NOW(), NOW()),
(9,  'https://loremflickr.com/800/800/cheddar,cheese?lock=9',    'جبنة تشيدر كتلة 200 جم', 0, 1, NOW(), NOW()),
(9,  'https://loremflickr.com/800/800/cheddar,cheese?lock=109',  'جبنة تشيدر كتلة 200 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(10, 'https://loremflickr.com/800/800/mozzarella,cheese?lock=10', 'جبنة موزاريلا 250 جم', 0, 1, NOW(), NOW()),
(10, 'https://loremflickr.com/800/800/mozzarella,cheese?lock=110', 'جبنة موزاريلا 250 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(11, 'https://loremflickr.com/800/800/eggs?lock=11',             'بيض حر المراعي (عبوة 12)', 0, 1, NOW(), NOW()),
(11, 'https://loremflickr.com/800/800/eggs?lock=111',            'بيض حر المراعي (عبوة 12) - صورة إضافية', 1, 0, NOW(), NOW()),
(12, 'https://loremflickr.com/800/800/eggs,carton?lock=12',      'بيض عضوي (عبوة 6)', 0, 1, NOW(), NOW()),
(12, 'https://loremflickr.com/800/800/eggs,carton?lock=112',     'بيض عضوي (عبوة 6) - صورة إضافية', 1, 0, NOW(), NOW()),
(13, 'https://loremflickr.com/800/800/bread,wheat?lock=13',      'رغيف خبز القمح الكامل', 0, 1, NOW(), NOW()),
(13, 'https://loremflickr.com/800/800/bread,wheat?lock=113',     'رغيف خبز القمح الكامل - صورة إضافية', 1, 0, NOW(), NOW()),
(14, 'https://loremflickr.com/800/800/bread,sandwich?lock=14',   'خبز التوست الأبيض', 0, 1, NOW(), NOW()),
(14, 'https://loremflickr.com/800/800/bread,sandwich?lock=114',  'خبز التوست الأبيض - صورة إضافية', 1, 0, NOW(), NOW()),
(15, 'https://loremflickr.com/800/800/croissant,chocolate?lock=15', 'كرواسون بالشوكولاتة', 0, 1, NOW(), NOW()),
(15, 'https://loremflickr.com/800/800/croissant,chocolate?lock=115', 'كرواسون بالشوكولاتة - صورة إضافية', 1, 0, NOW(), NOW()),
(16, 'https://loremflickr.com/800/800/muffin,blueberry?lock=16', 'مافن التوت الأزرق', 0, 1, NOW(), NOW()),
(16, 'https://loremflickr.com/800/800/muffin,blueberry?lock=116', 'مافن التوت الأزرق - صورة إضافية', 1, 0, NOW(), NOW()),
(17, 'https://loremflickr.com/800/800/chicken,breast?lock=17',   'صدور دجاج 1 كجم', 0, 1, NOW(), NOW()),
(17, 'https://loremflickr.com/800/800/chicken,breast?lock=117',  'صدور دجاج 1 كجم - صورة إضافية', 1, 0, NOW(), NOW()),
(18, 'https://loremflickr.com/800/800/chicken,whole?lock=18',    'دجاجة كاملة 1.5 كجم', 0, 1, NOW(), NOW()),
(18, 'https://loremflickr.com/800/800/chicken,whole?lock=118',   'دجاجة كاملة 1.5 كجم - صورة إضافية', 1, 0, NOW(), NOW()),
(19, 'https://loremflickr.com/800/800/beef,ground?lock=19',      'لحم بقري مفروم 500 جم', 0, 1, NOW(), NOW()),
(19, 'https://loremflickr.com/800/800/beef,ground?lock=119',     'لحم بقري مفروم 500 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(20, 'https://loremflickr.com/800/800/lamb,chops?lock=20',       'قطع ضأن 500 جم', 0, 1, NOW(), NOW()),
(20, 'https://loremflickr.com/800/800/lamb,chops?lock=120',      'قطع ضأن 500 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(21, 'https://loremflickr.com/800/800/salmon,fillet?lock=21',    'شرائح سلمون طازج 300 جم', 0, 1, NOW(), NOW()),
(21, 'https://loremflickr.com/800/800/salmon,fillet?lock=121',   'شرائح سلمون طازج 300 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(22, 'https://loremflickr.com/800/800/shrimp?lock=22',           'جمبري 500 جم', 0, 1, NOW(), NOW()),
(22, 'https://loremflickr.com/800/800/shrimp?lock=122',          'جمبري 500 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(23, 'https://loremflickr.com/800/800/rice,basmati?lock=23',     'أرز بسمتي 5 كجم', 0, 1, NOW(), NOW()),
(23, 'https://loremflickr.com/800/800/rice,basmati?lock=123',    'أرز بسمتي 5 كجم - صورة إضافية', 1, 0, NOW(), NOW()),
(24, 'https://loremflickr.com/800/800/quinoa?lock=24',           'كينوا 500 جم', 0, 1, NOW(), NOW()),
(24, 'https://loremflickr.com/800/800/quinoa?lock=124',          'كينوا 500 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(25, 'https://loremflickr.com/800/800/spaghetti,pasta?lock=25',  'سباغيتي 500 جم', 0, 1, NOW(), NOW()),
(25, 'https://loremflickr.com/800/800/spaghetti,pasta?lock=125', 'سباغيتي 500 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(26, 'https://loremflickr.com/800/800/penne,pasta?lock=26',      'معكرونة بيني 500 جم', 0, 1, NOW(), NOW()),
(26, 'https://loremflickr.com/800/800/penne,pasta?lock=126',     'معكرونة بيني 500 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(27, 'https://loremflickr.com/800/800/chickpeas?lock=27',        'حمص معلب 400 جم', 0, 1, NOW(), NOW()),
(27, 'https://loremflickr.com/800/800/chickpeas?lock=127',       'حمص معلب 400 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(28, 'https://loremflickr.com/800/800/tomato,canned?lock=28',    'طماطم مقطعة معلبة 400 جم', 0, 1, NOW(), NOW()),
(28, 'https://loremflickr.com/800/800/tomato,canned?lock=128',   'طماطم مقطعة معلبة 400 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(29, 'https://loremflickr.com/800/800/oliveoil?lock=29',         'زيت زيتون بكر ممتاز 1 لتر', 0, 1, NOW(), NOW()),
(29, 'https://loremflickr.com/800/800/oliveoil?lock=129',        'زيت زيتون بكر ممتاز 1 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(30, 'https://loremflickr.com/800/800/cookingoil?lock=30',       'زيت دوار الشمس 1 لتر', 0, 1, NOW(), NOW()),
(30, 'https://loremflickr.com/800/800/cookingoil?lock=130',      'زيت دوار الشمس 1 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(31, 'https://loremflickr.com/800/800/orangejuice?lock=31',      'عصير برتقال 1 لتر', 0, 1, NOW(), NOW()),
(31, 'https://loremflickr.com/800/800/orangejuice?lock=131',     'عصير برتقال 1 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(32, 'https://loremflickr.com/800/800/applejuice?lock=32',       'عصير تفاح 1 لتر', 0, 1, NOW(), NOW()),
(32, 'https://loremflickr.com/800/800/applejuice?lock=132',      'عصير تفاح 1 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(33, 'https://loremflickr.com/800/800/cola,soda?lock=33',        'كولا 1.5 لتر', 0, 1, NOW(), NOW()),
(33, 'https://loremflickr.com/800/800/cola,soda?lock=133',       'كولا 1.5 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(34, 'https://loremflickr.com/800/800/soda,lemon?lock=34',       'صودا الليمون 1.5 لتر', 0, 1, NOW(), NOW()),
(34, 'https://loremflickr.com/800/800/soda,lemon?lock=134',      'صودا الليمون 1.5 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(35, 'https://loremflickr.com/800/800/sparklingwater?lock=35',   'مياه غازية 1 لتر', 0, 1, NOW(), NOW()),
(35, 'https://loremflickr.com/800/800/sparklingwater?lock=135',  'مياه غازية 1 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(36, 'https://loremflickr.com/800/800/water,bottle?lock=36',     'مياه شرب طبيعية 6×500 مل', 0, 1, NOW(), NOW()),
(36, 'https://loremflickr.com/800/800/water,bottle?lock=136',    'مياه شرب طبيعية 6×500 مل - صورة إضافية', 1, 0, NOW(), NOW()),
(37, 'https://loremflickr.com/800/800/coffee,ground?lock=37',    'قهوة مطحونة 250 جم', 0, 1, NOW(), NOW()),
(37, 'https://loremflickr.com/800/800/coffee,ground?lock=137',   'قهوة مطحونة 250 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(38, 'https://loremflickr.com/800/800/greentea?lock=38',         'أكياس شاي أخضر (عبوة 20)', 0, 1, NOW(), NOW()),
(38, 'https://loremflickr.com/800/800/greentea?lock=138',        'أكياس شاي أخضر (عبوة 20) - صورة إضافية', 1, 0, NOW(), NOW()),
(39, 'https://loremflickr.com/800/800/potatochips?lock=39',      'رقائق بطاطس كلاسيكية 150 جم', 0, 1, NOW(), NOW()),
(39, 'https://loremflickr.com/800/800/potatochips?lock=139',     'رقائق بطاطس كلاسيكية 150 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(40, 'https://loremflickr.com/800/800/tortillachips?lock=40',    'رقائق تورتيلا 200 جم', 0, 1, NOW(), NOW()),
(40, 'https://loremflickr.com/800/800/tortillachips?lock=140',   'رقائق تورتيلا 200 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(41, 'https://loremflickr.com/800/800/chocolate,bar?lock=41',    'لوح شوكولاتة بالحليب 100 جم', 0, 1, NOW(), NOW()),
(41, 'https://loremflickr.com/800/800/chocolate,bar?lock=141',   'لوح شوكولاتة بالحليب 100 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(42, 'https://loremflickr.com/800/800/gummycandy?lock=42',       'حلوى جيلي متنوعة 250 جم', 0, 1, NOW(), NOW()),
(42, 'https://loremflickr.com/800/800/gummycandy?lock=142',      'حلوى جيلي متنوعة 250 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(43, 'https://loremflickr.com/800/800/frozenvegetables?lock=43', 'خضروات مشكلة مجمدة 1 كجم', 0, 1, NOW(), NOW()),
(43, 'https://loremflickr.com/800/800/frozenvegetables?lock=143', 'خضروات مشكلة مجمدة 1 كجم - صورة إضافية', 1, 0, NOW(), NOW()),
(44, 'https://loremflickr.com/800/800/peas,frozen?lock=44',      'بازلاء مجمدة 500 جم', 0, 1, NOW(), NOW()),
(44, 'https://loremflickr.com/800/800/peas,frozen?lock=144',     'بازلاء مجمدة 500 جم - صورة إضافية', 1, 0, NOW(), NOW()),
(45, 'https://loremflickr.com/800/800/vanillaicecream?lock=45',  'آيس كريم فانيليا 1 لتر', 0, 1, NOW(), NOW()),
(45, 'https://loremflickr.com/800/800/vanillaicecream?lock=145', 'آيس كريم فانيليا 1 لتر - صورة إضافية', 1, 0, NOW(), NOW()),
(46, 'https://loremflickr.com/800/800/chocolateicecream?lock=46', 'آيس كريم شوكولاتة 1 لتر', 0, 1, NOW(), NOW()),
(46, 'https://loremflickr.com/800/800/chocolateicecream?lock=146', 'آيس كريم شوكولاتة 1 لتر - صورة إضافية', 1, 0, NOW(), NOW());

-- ---------------------------------------------------------------------
-- Product variants: a "Standard" size and a "Family Pack" size per product
-- متغيرات المنتج: الحجم العادي وعبوة العائلة لكل منتج
-- ---------------------------------------------------------------------

INSERT INTO product_variants (product_id, sku, options, price, stock, is_active, created_at, updated_at)
SELECT p.id,
       CONCAT('GRO-', LPAD(p.id, 3, '0'), '-STD'),
       JSON_OBJECT('pack_size', 'الحجم العادي'),
       NULL,
       FLOOR(p.stock * 0.6),
       1,
       NOW(), NOW()
FROM products p;

INSERT INTO product_variants (product_id, sku, options, price, stock, is_active, created_at, updated_at)
VALUES
(1,  'GRO-001-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.49,  60, 1, NOW(), NOW()),
(2,  'GRO-002-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.49,  50, 1, NOW(), NOW()),
(3,  'GRO-003-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 5.49,  40, 1, NOW(), NOW()),
(4,  'GRO-004-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.29,  50, 1, NOW(), NOW()),
(5,  'GRO-005-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.99,  30, 1, NOW(), NOW()),
(6,  'GRO-006-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 2.69,  55, 1, NOW(), NOW()),
(7,  'GRO-007-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.49,  70, 1, NOW(), NOW()),
(8,  'GRO-008-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 6.49,  25, 1, NOW(), NOW()),
(9,  'GRO-009-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 10.99, 35, 1, NOW(), NOW()),
(10, 'GRO-010-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 8.49,  30, 1, NOW(), NOW()),
(11, 'GRO-011-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 5.49,  40, 1, NOW(), NOW()),
(12, 'GRO-012-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 6.49,  25, 1, NOW(), NOW()),
(13, 'GRO-013-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.49,  25, 1, NOW(), NOW()),
(14, 'GRO-014-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.49,  30, 1, NOW(), NOW()),
(15, 'GRO-015-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 7.99,  20, 1, NOW(), NOW()),
(16, 'GRO-016-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 6.99,  20, 1, NOW(), NOW()),
(17, 'GRO-017-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 12.99, 30, 1, NOW(), NOW()),
(18, 'GRO-018-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 13.49, 20, 1, NOW(), NOW()),
(19, 'GRO-019-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 10.99, 25, 1, NOW(), NOW()),
(20, 'GRO-020-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 18.99, 15, 1, NOW(), NOW()),
(21, 'GRO-021-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 14.99, 20, 1, NOW(), NOW()),
(22, 'GRO-022-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 16.99, 18, 1, NOW(), NOW()),
(23, 'GRO-023-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 22.99, 40, 1, NOW(), NOW()),
(24, 'GRO-024-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 9.99,  30, 1, NOW(), NOW()),
(25, 'GRO-025-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.29,  60, 1, NOW(), NOW()),
(26, 'GRO-026-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.29,  55, 1, NOW(), NOW()),
(27, 'GRO-027-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.99,  60, 1, NOW(), NOW()),
(28, 'GRO-028-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.49,  65, 1, NOW(), NOW()),
(29, 'GRO-029-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 16.99, 30, 1, NOW(), NOW()),
(30, 'GRO-030-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 5.99,  40, 1, NOW(), NOW()),
(31, 'GRO-031-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 5.49,  35, 1, NOW(), NOW()),
(32, 'GRO-032-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.99,  30, 1, NOW(), NOW()),
(33, 'GRO-033-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 7.99,  50, 1, NOW(), NOW()),
(34, 'GRO-034-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 7.99,  45, 1, NOW(), NOW()),
(35, 'GRO-035-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.99,  60, 1, NOW(), NOW()),
(36, 'GRO-036-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.49,  45, 1, NOW(), NOW()),
(37, 'GRO-037-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 10.99, 30, 1, NOW(), NOW()),
(38, 'GRO-038-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 5.99,  40, 1, NOW(), NOW()),
(39, 'GRO-039-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 8.99,  55, 1, NOW(), NOW()),
(40, 'GRO-040-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.99,  50, 1, NOW(), NOW()),
(41, 'GRO-041-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.99,  60, 1, NOW(), NOW()),
(42, 'GRO-042-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 4.49,  45, 1, NOW(), NOW()),
(43, 'GRO-043-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 5.99,  35, 1, NOW(), NOW()),
(44, 'GRO-044-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 3.49,  45, 1, NOW(), NOW()),
(45, 'GRO-045-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 7.99,  25, 1, NOW(), NOW()),
(46, 'GRO-046-FAM', JSON_OBJECT('pack_size', 'عبوة عائلية'), 7.99,  25, 1, NOW(), NOW());

COMMIT;
